name: "Set up Jolie environment"
description: "Set up a Jolie environment and add the command tools to the PATH"
author: "The Jolie Team"
branding:
  icon: "at-sign"
  color: "gray-dark"
inputs:
  version:
    description: "The Jolie version tag to set up. See Jolie's GitHub releases for available versions."
    default: "1.11.0"
  node-version:
    description: "The node version to set up"
    default: 16

runs:
  using: "composite"
  steps:
    - name: Set up Node (required for Jolie Package Manager)
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: "17"
        distribution: "temurin"
    - name: Download Jolie Release
      id: download-release
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "jolie/jolie"
        tag: "v${{ inputs.version }}"
        fileName: "*.jar"
        out-file-path: "jolie-installer.jar"
    - name: Install Jolie
      shell: bash
      run: |
        java -jar ${{ fromJson(steps.download-release.outputs.downloaded_files)[0] }} -jh ${{ github.action_path }}/jolie/dist -jl ${{ github.action_path }}/jolie/launchers
    - name: "Set up JOLIE_HOME environment"
      shell: bash
      run: |
        echo "JOLIE_HOME=${{ github.action_path }}/jolie/dist" >> "$GITHUB_ENV"
    - name: Set up PATH environment
      shell: bash
      run: |
        echo "${{ github.action_path }}/jolie/launchers" >> $GITHUB_PATH
    - name: Install JPM (Jolie Package Manager)
      shell: bash
      run: |
        npm install -g @jolie/jpm
